# Generated by Django 3.1.1 on 2020-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('year', models.PositiveIntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
